# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_path', models.CharField(max_length=2000)),
                ('received', models.CharField(max_length=2000)),
                ('x_ses_spam_verdict', models.CharField(max_length=2000)),
                ('x_ses_virus_verdict', models.CharField(max_length=2000)),
                ('received_spf', models.CharField(max_length=200)),
                ('authentication_results', models.CharField(max_length=200)),
                ('x_ses_receipt', models.CharField(max_length=200)),
                ('x_ses_dkim_signature', models.CharField(max_length=200)),
                ('dkim_signature', models.CharField(max_length=200)),
                ('x_google_dkim_signature', models.CharField(max_length=200)),
                ('x_gm_message_state', models.CharField(max_length=2000)),
                ('x_received', models.CharField(max_length=2000)),
                ('in_reply_to', models.CharField(max_length=2000)),
                ('references', models.CharField(max_length=2000)),
                ('from_field', models.CharField(max_length=2000)),
                ('date', models.CharField(max_length=2000)),
                ('message_id', models.CharField(max_length=2000)),
                ('subject', models.CharField(max_length=2000)),
                ('to', models.CharField(max_length=2000)),
                ('content_type', models.CharField(max_length=2000)),
            ],
        ),
    ]
