# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_mail', '0002_auto_20170527_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_info',
            name='mime_version',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
