# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_mail', '0005_auto_20170528_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_info',
            name='date',
            field=models.CharField(db_index=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='email_info',
            name='from_field',
            field=models.CharField(db_index=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='email_info',
            name='return_path',
            field=models.CharField(db_index=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='email_info',
            name='x_ses_spam_verdict',
            field=models.CharField(db_index=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='email_info',
            name='x_ses_virus_verdict',
            field=models.CharField(db_index=True, default='', max_length=2000),
        ),
    ]
